// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0b2H10jtcireYKxJT7dUuJ3ocPIAe2cI',
    appId: '1:399785821298:web:f0eaaad717f977c77caeeb',
    messagingSenderId: '399785821298',
    projectId: 'ilycode-44bd3',
    authDomain: 'ilycode-44bd3.firebaseapp.com',
    storageBucket: 'ilycode-44bd3.firebasestorage.app',
    measurementId: 'G-07V4R64P6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eO9_kYI7iQUK4iM0p-YyleU6HCgaDQo',
    appId: '1:399785821298:android:771ef36765679d357caeeb',
    messagingSenderId: '399785821298',
    projectId: 'ilycode-44bd3',
    storageBucket: 'ilycode-44bd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0c6IwSewlTLgpjwGXN18hRD7wbHTo1tY',
    appId: '1:399785821298:ios:4838427f5a6213847caeeb',
    messagingSenderId: '399785821298',
    projectId: 'ilycode-44bd3',
    storageBucket: 'ilycode-44bd3.firebasestorage.app',
    iosBundleId: 'com.example.flutterTopsisSmkinformatika',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0c6IwSewlTLgpjwGXN18hRD7wbHTo1tY',
    appId: '1:399785821298:ios:4838427f5a6213847caeeb',
    messagingSenderId: '399785821298',
    projectId: 'ilycode-44bd3',
    storageBucket: 'ilycode-44bd3.firebasestorage.app',
    iosBundleId: 'com.example.flutterTopsisSmkinformatika',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0b2H10jtcireYKxJT7dUuJ3ocPIAe2cI',
    appId: '1:399785821298:web:4cd028d6b49f45a77caeeb',
    messagingSenderId: '399785821298',
    projectId: 'ilycode-44bd3',
    authDomain: 'ilycode-44bd3.firebaseapp.com',
    storageBucket: 'ilycode-44bd3.firebasestorage.app',
    measurementId: 'G-KGGDT7MLF5',
  );
}